function [] = Setup()

current_dir = pwd();

cd(fullfile('../../matconvnet-1.0-beta16-gpu/', 'matlab'));
cuda_root = '/usr/local/cuda-8.0'; 
cudnn_root = '/home/enijkamp/cudnn-3.0'; 

vl_setupnn();

vl_compilenn('EnableGPU', true, ...
    'CudaRoot', cuda_root, ...
    'CudaMethod', 'nvcc', ...
    'enableCudnn', true, ...
    'cudnnRoot', cudnn_root);

% vl_compilenn('EnableGPU', true, ...
%     'CudaRoot', cuda_root, ...
%     'CudaMethod', 'nvcc', ...
%     'enableCudnn', false);


cd(current_dir);